-- Master schema for OneRingToRuleThemAll
-- Run once: psql -U homelab -d homelab -f db/migrations/001_master_schema.sql

CREATE SCHEMA IF NOT EXISTS master;

CREATE TABLE IF NOT EXISTS master.chat_messages (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     TEXT NOT NULL,
    role        TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'tool')),
    content     TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS chat_messages_user_created
    ON master.chat_messages (user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS master.chat_summary (
    user_id     TEXT PRIMARY KEY,
    summary     TEXT NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Role with read/write access to master schema + read on drophunter/public
DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'master_rw') THEN
        CREATE ROLE master_rw LOGIN PASSWORD 'changeme';
    END IF;
END $$;

GRANT USAGE ON SCHEMA master TO master_rw;
GRANT ALL ON ALL TABLES IN SCHEMA master TO master_rw;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA master TO master_rw;

GRANT USAGE ON SCHEMA public TO master_rw;
GRANT SELECT, UPDATE ON public.vehicles TO master_rw;
GRANT SELECT ON public.reminder_log TO master_rw;

GRANT USAGE ON SCHEMA drophunter TO master_rw;
GRANT SELECT ON drophunter.games TO master_rw;
GRANT SELECT ON drophunter.watches TO master_rw;
GRANT SELECT ON drophunter.price_history TO master_rw;
